# Generated by Django 4.0.6 on 2023-04-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_patientquestionaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQuestionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('question_number', models.CharField(max_length=50)),
                ('response', models.CharField(max_length=200)),
            ],
        ),
    ]
