# Generated by Django 4.0.6 on 2023-05-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patientquestionaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQuestionaireRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('riskMarker', models.FloatField(default=0.0)),
                ('PLR', models.FloatField(default=0.0)),
                ('TELR', models.FloatField(default=0.0)),
                ('PostProb', models.FloatField(default=0.0)),
                ('PPPD', models.CharField(max_length=20)),
                ('response', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientQuestionaire',
        ),
    ]
