# Generated by Django 4.0.6 on 2023-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patientquestionairerecord_delete_patientquestionaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='taking_pd_medicine',
        ),
        migrations.AddField(
            model_name='patient',
            name='patientId',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
