# Generated by Django 4.0.6 on 2023-05-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_patient_id_remove_patient_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
