# Generated by Django 4.0.6 on 2023-05-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patient_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
