# Generated by Django 4.0.6 on 2023-05-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_patient_patientid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['patientId'], 'permissions': (('view_patient_list', 'Can view patient list'),)},
        ),
        migrations.AddField(
            model_name='fileuploaded',
            name='patientId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddField(
            model_name='results',
            name='patientId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='patientquestionairerecord',
            name='patientId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patientId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
