# Generated by Django 4.0.6 on 2023-05-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_patient_options_fileuploaded_patientid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': (('view_patient_list', 'Can view patient list'),)},
        ),
        migrations.RemoveField(
            model_name='fileuploaded',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='results',
            name='patientId',
        ),
        migrations.AlterField(
            model_name='patientquestionairerecord',
            name='patientId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patientId',
            field=models.CharField(max_length=200),
        ),
    ]
