# Generated by Django 4.0.6 on 2023-07-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_patient_options_fileuploaded_patientid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
