# Generated by Django 4.0.6 on 2023-07-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patient_user_name_alter_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_no',
            field=models.CharField(default='', max_length=30),
        ),
    ]
